# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_townie_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townie',
            name='displayname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='townie',
            name='shell',
            field=models.CharField(default='/bin/bash', max_length=50),
        ),
    ]
