# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161121_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='townie',
            name='pending',
        ),
        migrations.AddField(
            model_name='townie',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
