# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161121_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='townie',
            name='pubkey_type',
            field=models.CharField(choices=[('ssh-rsa', 'ssh-rsa'), ('ssh-dss', 'ssh-dss')], default='ssh-rsa', max_length=15),
            preserve_default=False,
        ),
    ]
