# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_townie_pubkey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='townie',
            name='reasons',
            field=models.TextField(blank=True, default=''),
        ),
    ]
