# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170113_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pubkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('ssh-rsa', 'ssh-rsa'), ('ssh-dss', 'ssh-dss')], max_length=15)),
                ('key', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='townie',
            name='pubkey',
        ),
        migrations.AddField(
            model_name='pubkey',
            name='townie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Townie'),
        ),
    ]
