# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170113_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubkey',
            name='key_type',
            field=models.CharField(choices=[('ssh-rsa', 'ssh-rsa'), ('ssh-dss', 'ssh-dss')], max_length=50),
        ),
    ]
